name: Deploy Site Static

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm ci --legacy-peer-deps # Will need to keep this until svelte5 release

      - name: Build
        run: npm run build

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
